tap "buo/cask-upgrade"
tap "derailed/k9s"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "jsdelivr/globalping"
tap "lihaoyun6/tap"
tap "th-ch/youtube-music"
# Simple, modern, secure file encryption
brew "age"
# Mozilla CA certificate store
brew "ca-certificates"
# Download with resuming and segmented downloading
brew "aria2"
# General-purpose data compression with high compression ratio
brew "xz"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Record and share terminal sessions
brew "asciinema"
# Code searching, linting, rewriting
brew "ast-grep"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# New way of working with Protocol Buffers
brew "buf"
# Mozilla CA bundle for Python
brew "certifi"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Tool for exploring each layer in a docker image
brew "dive"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Highly customizable changelog generator
brew "git-cliff"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Git extension for versioning large files
brew "git-lfs"
# Open-source GitLab command-line tool
brew "glab"
# Validating, recursive, caching DNS resolver
brew "unbound"
# X.509 and CMS library
brew "libksba"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Command-line interface for Hetzner Cloud
brew "hcloud"
# Improved top (interactive process viewer)
brew "htop"
# Command-line benchmarking tool
brew "hyperfine"
# Update of iperf: measures TCP, UDP, and SCTP bandwidth
brew "iperf3"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Handy way to save and run project-specific commands
brew "just"
# Modern load testing tool, using Go and JavaScript
brew "k6"
# Save disk space by cleaning non-essential files from software projects
brew "kondo"
# Network authentication protocol
brew "krb5"
# Simple terminal UI for git commands
brew "lazygit"
# C library for reading, creating, and modifying zip archives
brew "libzip"
# Mac App Store command-line interface
brew "mas"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Open source visual route tracking CLI tool
brew "nexttrace"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node@20"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Fast, disk space efficient package manager
brew "pnpm"
# Object-relational database system
brew "postgresql@15"
# Modern replacement for ps written by Rust
brew "procs"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Persistent key-value database, with built-in net interface
brew "redis"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Generate type safe Go from SQL
brew "sqlc"
# CLI for extracting streams from various websites to a video player
brew "streamlink"
# Log file highlighter
brew "tailspin"
# User interface to the TELNET protocol
brew "telnet"
# Official tldr client written in Rust
brew "tlrc"
# Program that allows you to count code, quickly
brew "tokei"
# CLI tool that moves files or folder to the trash
brew "trash"
# Network diagnostic tool, inspired by mtr
brew "trippy"
# Generate WireGuard profile from Cloudflare Warp account
brew "wgcf"
# Lookup tool for domain names and other internet resources
brew "whois"
# Check your $HOME for unwanted files and directories
brew "xdg-ninja", args: ["HEAD"]
# Friendly and fast tool for sending HTTP requests
brew "xh"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "derailed/k9s/k9s"
brew "jsdelivr/globalping/globalping"
# GPU-accelerated terminal emulator
cask "alacritty"
# Android SDK component
cask "android-platform-tools"
# Display management tool
cask "betterdisplay"
# Free app that makes your Internet safer
cask "cloudflare-warp"
# Voice and text chat software
cask "discord"
# Collaborative team software
cask "figma"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-lxgw-wenkai"
cask "font-sauce-code-pro-nerd-font"
# Desktop automation application
cask "hammerspoon"
# Free and open-source media player
cask "iina"
# Open-source keystroke visualiser
cask "keycastr"
# App to write, plan, collaborate, and get organised
cask "notion"
# Quick Look plugin for plaintext files without an extension
cask "qlstephen"
# Quick Look plugin for JSON files
cask "quicklook-json"
# A lightweight and high-performance screen recorder for macOS.
cask "quickrecorder"
# Open source virtual/remote desktop application
cask "rustdesk"
# Standalone client for sing-box, the universal proxy platform
cask "sfm"
# Rime input method engine
cask "squirrel"
# Real time file synchronisation software
cask "syncthing"
# JDK from the Eclipse Foundation (Adoptium)
cask "temurin@21"
# Cloud video conferencing
cask "tencent-meeting"
# Quick Look plugin for webp files
cask "webpquicklook"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# YouTube Music Desktop App
cask "youtube-music"
mas "APTV", id: 1630403500
mas "Bob", id: 1630034110
mas "Cubox", id: 1113361350
mas "LocalSend", id: 1661733229
mas "Microsoft Remote Desktop", id: 1295203466
mas "PasteNow", id: 1552536109
mas "Stay", id: 1591620171
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "TickTick", id: 966085870
vscode "astro-build.astro-vscode"
vscode "bradlc.vscode-tailwindcss"
vscode "chakrounanas.turbo-console-log"
vscode "christian-kohler.path-intellisense"
vscode "codeium.codeium"
vscode "dbaeumer.vscode-eslint"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.code-runner"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "humao.rest-client"
vscode "lokalise.i18n-ally"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "pkief.material-icon-theme"
vscode "ritwickdey.liveserver"
vscode "usernamehw.errorlens"
vscode "vue.volar"
